"""empty message

Revision ID: 307d30873ba2
Revises: 9459a5a3dd32
Create Date: 2020-07-03 20:14:33.640296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307d30873ba2'
down_revision = '9459a5a3dd32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.drop_constraint(u'Show_right_id_fkey', 'Show', type_='foreignkey')
    op.create_foreign_key(None, 'Show', 'Artist', ['artist_id'], ['id'])
    op.drop_column('Show', 'right_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('right_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.create_foreign_key(u'Show_right_id_fkey', 'Show', 'Artist', ['right_id'], ['id'])
    op.drop_column('Show', 'artist_id')
    # ### end Alembic commands ###
