"""empty message

Revision ID: 4213bae3f3f5
Revises: 74f7c421e418
Create Date: 2020-07-03 19:43:52.060000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4213bae3f3f5'
down_revision = '74f7c421e418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('right_id', sa.Integer(), nullable=False))
    op.add_column('Show', sa.Column('show_time', sa.String(length=50), nullable=True))
    op.drop_constraint(u'Show_artist_id_fkey', 'Show', type_='foreignkey')
    op.create_foreign_key(None, 'Show', 'Artist', ['right_id'], ['id'])
    op.drop_column('Show', 'artist_id')
    op.drop_column('Show', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('Show', sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.create_foreign_key(u'Show_artist_id_fkey', 'Show', 'Artist', ['artist_id'], ['id'])
    op.drop_column('Show', 'show_time')
    op.drop_column('Show', 'right_id')
    # ### end Alembic commands ###
