"""empty message

Revision ID: 74f7c421e418
Revises: 9b03150ac5b0
Create Date: 2020-07-03 18:10:53.574976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74f7c421e418'
down_revision = '9b03150ac5b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'time')
    # ### end Alembic commands ###
