"""empty message

Revision ID: e6d4f9d9f220
Revises: 7f49a551f219
Create Date: 2020-07-17 17:26:30.947138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6d4f9d9f220'
down_revision = '7f49a551f219'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('Show', sa.Column('id', sa.Integer(), nullable=True))
    op.execute('ALTER TABLE "Show" ADD COLUMN ID SERIAL PRIMARY KEY;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'id')
    # ### end Alembic commands ###
