"""empty message

Revision ID: ef7d0245160f
Revises: 4213bae3f3f5
Create Date: 2020-07-03 19:49:59.785281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef7d0245160f'
down_revision = '4213bae3f3f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Show')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('right_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('show_time', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['right_id'], [u'Artist.id'], name=u'Show_right_id_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], [u'Venue.id'], name=u'Show_venue_id_fkey')
    )
    # ### end Alembic commands ###
